/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export type AdminNotificationDtoType = typeof AdminNotificationDtoType[keyof typeof AdminNotificationDtoType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminNotificationDtoType = {
  global: 'global',
  hostel: 'hostel',
} as const;
