/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export interface CreateReviewDto {
  hostel_id: number;
  /** Rating from 1 to 5 */
  rating: number;
  comment?: string;
}
