/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export type CreateStudySpaceDtoStatus = typeof CreateStudySpaceDtoStatus[keyof typeof CreateStudySpaceDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateStudySpaceDtoStatus = {
  open: 'open',
  closed: 'closed',
  full: 'full',
} as const;
