/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */
import type { CreateRoomResourceDto } from './createRoomResourceDto';

export interface CreateRoomDto {
  room_number: string;
  capacity: number;
  price: number;
  availability?: boolean;
  resources?: CreateRoomResourceDto[];
}
