/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */
import type { CreateHostelResourceDtoFileType } from './createHostelResourceDtoFileType';

export interface CreateHostelResourceDto {
  file_url: string;
  file_type: CreateHostelResourceDtoFileType;
}
