/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export type CreateHostelResourceDtoFileType = typeof CreateHostelResourceDtoFileType[keyof typeof CreateHostelResourceDtoFileType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateHostelResourceDtoFileType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
} as const;
