/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export type CreateRoomResourceDtoFileType = typeof CreateRoomResourceDtoFileType[keyof typeof CreateRoomResourceDtoFileType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRoomResourceDtoFileType = {
  IMAGE: 'IMAGE',
  VIDEO: 'VIDEO',
  PDF: 'PDF',
} as const;
