/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export interface CreatePaymentIntentDto {
  /** Amount in dollars */
  amount: number;
  /** The ID of the room being booked */
  roomId: string;
  /** The ID of the student */
  studentId: string;
}
