/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export interface ErrorResponseDto {
  /** Indicates if the request was successful */
  success: boolean;
  /** The error message returned by the server */
  message: string;
  /** The HTTP status code (e.g., 400, 401, 403, 500) */
  statusCode: number;
}
