/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export type GoogleLoginDtoRole = typeof GoogleLoginDtoRole[keyof typeof GoogleLoginDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoogleLoginDtoRole = {
  student: 'student',
  hostelOwner: 'hostelOwner',
} as const;
