/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */
import type { GoogleLoginDtoRole } from './googleLoginDtoRole';

export interface GoogleLoginDto {
  /** Google ID Token */
  idToken: string;
  role: GoogleLoginDtoRole;
  phone?: string;
}
