/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export * from './adminControllerGetAllHostelsParams';
export * from './adminControllerGetAllMaintenanceParams';
export * from './adminControllerGetAllNotificationsParams';
export * from './adminControllerGetAllOwnersParams';
export * from './adminControllerGetAllReviewsParams';
export * from './adminControllerGetAllStudentsParams';
export * from './adminControllerGetPendingBookingsParams';
export * from './adminData';
export * from './adminLoginDto';
export * from './adminNotificationDto';
export * from './adminNotificationDtoType';
export * from './adminResponseDto';
export * from './authResponseDto';
export * from './cloudinaryControllerGetSignatureParams';
export * from './cloudinarySignatureResponseDto';
export * from './createBookingDto';
export * from './createHostelDto';
export * from './createHostelResourceDto';
export * from './createHostelResourceDtoFileType';
export * from './createMaintenanceDto';
export * from './createPaymentIntentDto';
export * from './createReviewDto';
export * from './createRoomDto';
export * from './createRoomResourceDto';
export * from './createRoomResourceDtoFileType';
export * from './createStudySpaceDto';
export * from './createStudySpaceDtoStatus';
export * from './errorResponseDto';
export * from './forgotPasswordDto';
export * from './googleLoginDto';
export * from './googleLoginDtoRole';
export * from './hostelControllerGetHostelMaintenanceParams';
export * from './hostelControllerGetHostelReviewsParams';
export * from './hostelControllerGetMyHostelsParams';
export * from './hostelControllerGetOwnerBookingsParams';
export * from './hostelControllerGetRoomsByHostelParams';
export * from './loginDto';
export * from './messageResponseDto';
export * from './messageResponseDtoData';
export * from './ownerNotificationDto';
export * from './paymentIntentResponseDto';
export * from './registerDto';
export * from './registerDtoRole';
export * from './rejectHostelDto';
export * from './replyReviewDto';
export * from './resendOtpDto';
export * from './resetPasswordDto';
export * from './studentControllerGetAvailableHostelsParams';
export * from './studentControllerGetAvailableRoomsParams';
export * from './studentControllerGetAvailableRoomsSort';
export * from './studentControllerGetAvailableStudySpacesParams';
export * from './studentControllerGetAvailableStudySpacesStatus';
export * from './studentControllerGetMyBookingsParams';
export * from './studentControllerGetMyMaintenanceParams';
export * from './studentControllerGetMyNotificationsParams';
export * from './studentControllerGetMyReviewsParams';
export * from './updateHostelDto';
export * from './updateMaintenanceStatusDto';
export * from './updateMaintenanceStatusDtoStatus';
export * from './updateProfileDto';
export * from './updateRoomDto';
export * from './updateStudySpaceDto';
export * from './updateStudySpaceDtoStatus';
export * from './userData';
export * from './userProfileResponseDto';
export * from './verifyOtpDto';