/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export * from './adminData';
export * from './adminLoginDto';
export * from './adminResponseDto';
export * from './authResponseDto';
export * from './cloudinaryControllerGetSignatureParams';
export * from './cloudinarySignatureResponseDto';
export * from './createBookingDto';
export * from './createHostelDto';
export * from './createHostelResourceDto';
export * from './createHostelResourceDtoFileType';
export * from './createRoomDto';
export * from './createRoomResourceDto';
export * from './createRoomResourceDtoFileType';
export * from './errorResponseDto';
export * from './forgotPasswordDto';
export * from './googleLoginDto';
export * from './googleLoginDtoRole';
export * from './hostelControllerGetMyHostelsParams';
export * from './hostelControllerGetOwnerBookingsParams';
export * from './hostelControllerGetRoomsByHostelParams';
export * from './loginDto';
export * from './messageResponseDto';
export * from './messageResponseDtoData';
export * from './registerDto';
export * from './registerDtoRole';
export * from './resendOtpDto';
export * from './resetPasswordDto';
export * from './studentControllerGetAvailableHostelsParams';
export * from './studentControllerGetAvailableRoomsParams';
export * from './studentControllerGetAvailableRoomsSort';
export * from './studentControllerGetMyBookingsParams';
export * from './updateHostelDto';
export * from './updateProfileDto';
export * from './updateRoomDto';
export * from './userData';
export * from './userProfileResponseDto';
export * from './verifyOtpDto';