/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */
import type { StudentControllerGetAvailableRoomsSort } from './studentControllerGetAvailableRoomsSort';

export type StudentControllerGetAvailableRoomsParams = {
limit?: number;
page?: number;
sort?: StudentControllerGetAvailableRoomsSort;
capacity?: number;
price?: number;
hostel_id?: number;
};
