/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export type StudentControllerGetAvailableRoomsSort = typeof StudentControllerGetAvailableRoomsSort[keyof typeof StudentControllerGetAvailableRoomsSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StudentControllerGetAvailableRoomsSort = {
  price_asc: 'price_asc',
  price_desc: 'price_desc',
} as const;
