/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */
import type { UpdateStudySpaceDtoStatus } from './updateStudySpaceDtoStatus';

export interface UpdateStudySpaceDto {
  name?: string;
  location?: string;
  total_capacity?: number;
  available_slots?: number;
  status?: UpdateStudySpaceDtoStatus;
  opening_time?: string;
  closing_time?: string;
}
