/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export type UpdateMaintenanceStatusDtoStatus = typeof UpdateMaintenanceStatusDtoStatus[keyof typeof UpdateMaintenanceStatusDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateMaintenanceStatusDtoStatus = {
  pending: 'pending',
  in_progress: 'in_progress',
  resolved: 'resolved',
  rejected: 'rejected',
} as const;
