/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Student Welfare Platform API
 * The API documentation for the Student Welfare Platform
 * OpenAPI spec version: 1.0
 */

export interface UserData {
  id: number;
  email: string;
  role: string;
  firstName: string;
  lastName: string;
  /** @nullable */
  image: string | null;
}
